name: Gitclaw Agent

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

permissions:
  contents: write
  issues: write
  actions: write

jobs:
  run-agent:
    runs-on: ubuntu-latest
    if: >
      (
        github.event_name == 'issues' &&
        contains(fromJSON('["OWNER","MEMBER","COLLABORATOR"]'), github.event.issue.author_association)
      ) ||
      (
        github.event_name == 'issue_comment' &&
        github.event.comment.user.login != 'github-actions[bot]' &&
        contains(fromJSON('["OWNER","MEMBER","COLLABORATOR"]'), github.event.comment.author_association)
      )
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Preinstall
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bun lifecycle/preinstall.ts

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bun lifecycle/main.ts --provider google --model gemini-pro
